package net.fellter.vanillalayerplus.registry;

import net.minecraft.client.resources.model.sprite.Material;
import java.util.LinkedHashMap;
import java.util.Map;

import net.fellter.vanillalayerplus.block.ModBlocks;
import net.minecraft.world.item.DyeColor;
import net.minecraft.client.color.item.Constant;
import net.minecraft.client.color.item.GrassColorSource;
import net.minecraft.client.data.models.model.TextureMapping;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import static net.fellter.vanillalayerplus.util.ModTextureMap.*;

public final class Args {
	public static Map<Block, DatagenArgs> DATAGEN_ARGS = new LinkedHashMap<>();
	public static Map<Block, RegistryArgs> REGISTRY_ARGS = new LinkedHashMap<>();

	private static void putInDatagenArgs(Block block, DatagenArgs datagenArgs) {
		DatagenArgs oldArgs = DATAGEN_ARGS.put(block, datagenArgs);

		if (oldArgs == null) {
			DATAGEN_ARGS.put(block, datagenArgs);
		} else {
			throw new IllegalStateException("Block " + block.getName() + " has already been put in DatagenArgs source map.");
		}
	}

	private static void putInRegistryArgs(Block block, RegistryArgs registryArgs) {
		RegistryArgs oldArgs = REGISTRY_ARGS.put(block, registryArgs);

		if (oldArgs == null) {
			REGISTRY_ARGS.put(block, registryArgs);
		} else {
			throw new IllegalStateException("Block " + block.getName() + " has already been put in RegistryArgs source map.");
		}
	}

	public static void registerDatagenArgs() {
		putInDatagenArgs(ModBlocks.OAK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.OAK_PLANKS).textureMap(TextureMapping.cube(Blocks.OAK_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_OAK_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_OAK_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_OAK_LOG)));
		putInDatagenArgs(ModBlocks.OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.OAK_LOG).textureMap(blockAndTopForEnds(Blocks.OAK_LOG)));
		putInDatagenArgs(ModBlocks.OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.OAK_WOOD).textureMap(TextureMapping.cube(Blocks.OAK_LOG)));
		putInDatagenArgs(ModBlocks.SPRUCE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.SPRUCE_PLANKS).textureMap(TextureMapping.cube(Blocks.SPRUCE_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_SPRUCE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_SPRUCE_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_SPRUCE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_SPRUCE_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.SPRUCE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.SPRUCE_LOG).textureMap(blockAndTopForEnds(Blocks.SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.SPRUCE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.SPRUCE_WOOD).textureMap(TextureMapping.cube(Blocks.SPRUCE_LOG)));
		putInDatagenArgs(ModBlocks.BIRCH_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BIRCH_PLANKS).textureMap(TextureMapping.cube(Blocks.BIRCH_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_BIRCH_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_BIRCH_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_BIRCH_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_BIRCH_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.BIRCH_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BIRCH_LOG).textureMap(blockAndTopForEnds(Blocks.BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.BIRCH_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BIRCH_WOOD).textureMap(TextureMapping.cube(Blocks.BIRCH_LOG)));
		putInDatagenArgs(ModBlocks.JUNGLE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.JUNGLE_PLANKS).textureMap(TextureMapping.cube(Blocks.JUNGLE_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_JUNGLE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_JUNGLE_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_JUNGLE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_JUNGLE_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.JUNGLE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.JUNGLE_LOG).textureMap(blockAndTopForEnds(Blocks.JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.JUNGLE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.JUNGLE_WOOD).textureMap(TextureMapping.cube(Blocks.JUNGLE_LOG)));
		putInDatagenArgs(ModBlocks.ACACIA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.ACACIA_PLANKS).textureMap(TextureMapping.cube(Blocks.ACACIA_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_ACACIA_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_ACACIA_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_ACACIA_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_ACACIA_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.ACACIA_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.ACACIA_LOG).textureMap(blockAndTopForEnds(Blocks.ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.ACACIA_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.ACACIA_WOOD).textureMap(TextureMapping.cube(Blocks.ACACIA_LOG)));
		putInDatagenArgs(ModBlocks.DARK_OAK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.DARK_OAK_PLANKS).textureMap(TextureMapping.cube(Blocks.DARK_OAK_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_DARK_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_DARK_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_DARK_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_DARK_OAK_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.DARK_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.DARK_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.DARK_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.DARK_OAK_WOOD).textureMap(TextureMapping.cube(Blocks.DARK_OAK_LOG)));
		putInDatagenArgs(ModBlocks.MANGROVE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.MANGROVE_PLANKS).textureMap(TextureMapping.cube(Blocks.MANGROVE_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_MANGROVE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_MANGROVE_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_MANGROVE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_MANGROVE_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.MANGROVE_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.MANGROVE_LOG).textureMap(blockAndTopForEnds(Blocks.MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.MANGROVE_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.MANGROVE_WOOD).textureMap(TextureMapping.cube(Blocks.MANGROVE_LOG)));
		putInDatagenArgs(ModBlocks.CHERRY_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.CHERRY_PLANKS).textureMap(TextureMapping.cube(Blocks.CHERRY_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_CHERRY_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_CHERRY_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_CHERRY_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_CHERRY_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.CHERRY_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.CHERRY_LOG).textureMap(blockAndTopForEnds(Blocks.CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.CHERRY_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.CHERRY_WOOD).textureMap(TextureMapping.cube(Blocks.CHERRY_LOG)));
		putInDatagenArgs(ModBlocks.PALE_OAK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.PALE_OAK_PLANKS).textureMap(TextureMapping.cube(Blocks.PALE_OAK_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_PALE_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_PALE_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.STRIPPED_PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.STRIPPED_PALE_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_PALE_OAK_WOOD).textureMap(TextureMapping.cube(Blocks.STRIPPED_PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.PALE_OAK_LOG_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.PALE_OAK_LOG).textureMap(blockAndTopForEnds(Blocks.PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.PALE_OAK_WOOD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.PALE_OAK_WOOD).textureMap(TextureMapping.cube(Blocks.PALE_OAK_LOG)));
		putInDatagenArgs(ModBlocks.BAMBOO_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BAMBOO_PLANKS).textureMap(TextureMapping.cube(Blocks.BAMBOO_PLANKS)));
		putInDatagenArgs(ModBlocks.BAMBOO_MOSAIC_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BAMBOO_MOSAIC).textureMap(TextureMapping.cube(Blocks.BAMBOO_MOSAIC)));
		putInDatagenArgs(ModBlocks.STRIPPED_BAMBOO_BLOCK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_BAMBOO_BLOCK).textureMap(blockAndTopForEnds(Blocks.STRIPPED_BAMBOO_BLOCK)));
		putInDatagenArgs(ModBlocks.BAMBOO_BLOCK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BAMBOO_BLOCK).textureMap(blockAndTopForEnds(Blocks.BAMBOO_BLOCK)));
		putInDatagenArgs(ModBlocks.CRIMSON_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.CRIMSON_PLANKS).textureMap(TextureMapping.cube(Blocks.CRIMSON_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_CRIMSON_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_CRIMSON_STEM).textureMap(blockAndTopForEnds(Blocks.STRIPPED_CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.STRIPPED_CRIMSON_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_CRIMSON_HYPHAE).textureMap(TextureMapping.cube(Blocks.STRIPPED_CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.CRIMSON_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.CRIMSON_STEM).textureMap(blockAndTopForEnds(Blocks.CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.CRIMSON_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.CRIMSON_HYPHAE).textureMap(TextureMapping.cube(Blocks.CRIMSON_STEM)));
		putInDatagenArgs(ModBlocks.WARPED_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.WARPED_PLANKS).textureMap(TextureMapping.cube(Blocks.WARPED_PLANKS)));
		putInDatagenArgs(ModBlocks.STRIPPED_WARPED_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_WARPED_STEM).textureMap(blockAndTopForEnds(Blocks.STRIPPED_WARPED_STEM)));
		putInDatagenArgs(ModBlocks.STRIPPED_WARPED_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.STRIPPED_WARPED_HYPHAE).textureMap(TextureMapping.cube(Blocks.STRIPPED_WARPED_STEM)));
		putInDatagenArgs(ModBlocks.WARPED_STEM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.WARPED_STEM).textureMap(blockAndTopForEnds(Blocks.WARPED_STEM)));
		putInDatagenArgs(ModBlocks.WARPED_HYPHAE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.WARPED_HYPHAE).textureMap(TextureMapping.cube(Blocks.WARPED_STEM)));
		putInDatagenArgs(ModBlocks.STONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STONE).textureMap(TextureMapping.cube(Blocks.STONE)).stonecutting());
		putInDatagenArgs(ModBlocks.COBBLESTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COBBLESTONE).textureMap(TextureMapping.cube(Blocks.COBBLESTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.MOSSY_COBBLESTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.MOSSY_COBBLESTONE).textureMap(TextureMapping.cube(Blocks.MOSSY_COBBLESTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.SMOOTH_STONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SMOOTH_STONE).textureMap(TextureMapping.cube(Blocks.SMOOTH_STONE)).stonecutting());
		putInDatagenArgs(ModBlocks.STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STONE_BRICKS).textureMap(TextureMapping.cube(Blocks.STONE_BRICKS)).stonecutting(Blocks.STONE));
		putInDatagenArgs(ModBlocks.CRACKED_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRACKED_STONE_BRICKS).textureMap(TextureMapping.cube(Blocks.CRACKED_STONE_BRICKS)));
		putInDatagenArgs(ModBlocks.CHISELED_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRACKED_STONE_BRICKS).textureMap(TextureMapping.cube(Blocks.CHISELED_STONE_BRICKS)).stonecutting(Blocks.STONE, Blocks.STONE_BRICKS));
		putInDatagenArgs(ModBlocks.MOSSY_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.MOSSY_STONE_BRICKS).textureMap(TextureMapping.cube(Blocks.MOSSY_STONE_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.GRANITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GRANITE).textureMap(TextureMapping.cube(Blocks.GRANITE)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_GRANITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_GRANITE).textureMap(TextureMapping.cube(Blocks.POLISHED_GRANITE)).stonecutting(Blocks.GRANITE));
		putInDatagenArgs(ModBlocks.DIORITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DIORITE).textureMap(TextureMapping.cube(Blocks.DIORITE)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_DIORITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_DIORITE).textureMap(TextureMapping.cube(Blocks.POLISHED_DIORITE)).stonecutting(Blocks.DIORITE));
		putInDatagenArgs(ModBlocks.ANDESITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.ANDESITE).textureMap(TextureMapping.cube(Blocks.ANDESITE)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_ANDESITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_ANDESITE).textureMap(TextureMapping.cube(Blocks.POLISHED_ANDESITE)).stonecutting(Blocks.ANDESITE));
		putInDatagenArgs(ModBlocks.DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE).textureMap(blockAndTopForEnds(Blocks.DEEPSLATE)));
		putInDatagenArgs(ModBlocks.REINFORCED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.REINFORCED_DEEPSLATE).textureMap(blockSTB(Blocks.REINFORCED_DEEPSLATE)));
		putInDatagenArgs(ModBlocks.COBBLED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COBBLED_DEEPSLATE).textureMap(TextureMapping.cube(Blocks.COBBLED_DEEPSLATE)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_DEEPSLATE).textureMap(TextureMapping.cube(Blocks.CHISELED_DEEPSLATE)).stonecutting(Blocks.COBBLED_DEEPSLATE));
		putInDatagenArgs(ModBlocks.POLISHED_DEEPSLATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_DEEPSLATE).textureMap(TextureMapping.cube(Blocks.POLISHED_DEEPSLATE)).stonecutting());
		putInDatagenArgs(ModBlocks.DEEPSLATE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_BRICKS).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_BRICKS)).stonecutting(Blocks.COBBLED_DEEPSLATE, Blocks.POLISHED_DEEPSLATE));
		putInDatagenArgs(ModBlocks.CRACKED_DEEPSLATE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRACKED_DEEPSLATE_BRICKS).textureMap(TextureMapping.cube(Blocks.CRACKED_DEEPSLATE_BRICKS)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_TILES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_TILES).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_TILES)).stonecutting(Blocks.POLISHED_DEEPSLATE, Blocks.DEEPSLATE_BRICKS));
		putInDatagenArgs(ModBlocks.CRACKED_DEEPSLATE_TILES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRACKED_DEEPSLATE_TILES).textureMap(TextureMapping.cube(Blocks.CRACKED_DEEPSLATE_TILES)));
		putInDatagenArgs(ModBlocks.TUFF_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.TUFF).textureMap(TextureMapping.cube(Blocks.TUFF)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_TUFF_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_TUFF).textureMap(blockAndTopForEnds(Blocks.CHISELED_TUFF)).stonecutting(Blocks.TUFF));
		putInDatagenArgs(ModBlocks.POLISHED_TUFF_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_TUFF).textureMap(TextureMapping.cube(Blocks.POLISHED_TUFF)).stonecutting(Blocks.TUFF));
		putInDatagenArgs(ModBlocks.TUFF_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.TUFF_BRICKS).textureMap(TextureMapping.cube(Blocks.TUFF_BRICKS)).stonecutting(Blocks.POLISHED_TUFF, Blocks.TUFF));
		putInDatagenArgs(ModBlocks.CHISELED_TUFF_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_TUFF_BRICKS).textureMap(blockAndTopForEnds(Blocks.CHISELED_TUFF_BRICKS)).stonecutting(Blocks.POLISHED_TUFF, Blocks.TUFF_BRICKS));
		putInDatagenArgs(ModBlocks.CINNABAR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CINNABAR).textureMap(TextureMapping.cube(Blocks.CINNABAR)).stonecutting());
		putInDatagenArgs(ModBlocks.POLISHED_CINNABAR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_CINNABAR).textureMap(TextureMapping.cube(Blocks.POLISHED_CINNABAR)).stonecutting(Blocks.CINNABAR));
		putInDatagenArgs(ModBlocks.CINNABAR_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CINNABAR_BRICKS).textureMap(TextureMapping.cube(Blocks.CINNABAR_BRICKS)).stonecutting(Blocks.CINNABAR, Blocks.POLISHED_CINNABAR));
		putInDatagenArgs(ModBlocks.CHISELED_CINNABAR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_CINNABAR).textureMap(TextureMapping.cube(Blocks.CHISELED_CINNABAR)).stonecutting(Blocks.CINNABAR));

		putInDatagenArgs(ModBlocks.SULFUR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SULFUR).textureMap(TextureMapping.cube(Blocks.SULFUR)).stonecutting());
		putInDatagenArgs(ModBlocks.POTENT_SULFUR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POTENT_SULFUR).textureMap(TextureMapping.cube(Blocks.POTENT_SULFUR)));
		putInDatagenArgs(ModBlocks.POLISHED_SULFUR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_SULFUR).textureMap(TextureMapping.cube(Blocks.POLISHED_SULFUR)).stonecutting(Blocks.SULFUR));
		putInDatagenArgs(ModBlocks.SULFUR_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SULFUR_BRICKS).textureMap(TextureMapping.cube(Blocks.SULFUR_BRICKS)).stonecutting(Blocks.SULFUR, Blocks.POLISHED_SULFUR));
		putInDatagenArgs(ModBlocks.CHISELED_SULFUR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_SULFUR).textureMap(TextureMapping.cube(Blocks.CHISELED_SULFUR)).stonecutting(Blocks.SULFUR));

		putInDatagenArgs(ModBlocks.BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BRICKS).textureMap(TextureMapping.cube(Blocks.BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.PACKED_MUD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.PACKED_MUD).textureMap(TextureMapping.cube(Blocks.PACKED_MUD)));
		putInDatagenArgs(ModBlocks.MUD_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.MUD_BRICKS).textureMap(TextureMapping.cube(Blocks.MUD_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.RESIN_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.RESIN_BRICKS).textureMap(TextureMapping.cube(Blocks.RESIN_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_RESIN_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_RESIN_BRICKS).textureMap(TextureMapping.cube(Blocks.CHISELED_RESIN_BRICKS)).stonecutting(Blocks.RESIN_BRICKS));
		putInDatagenArgs(ModBlocks.SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SANDSTONE).textureMap(blockTB(Blocks.SANDSTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_SANDSTONE).textureMap(custom(Blocks.CHISELED_SANDSTONE, Blocks.SANDSTONE, Blocks.SANDSTONE, "", "_top", "_top")).stonecutting(Blocks.SANDSTONE));
		putInDatagenArgs(ModBlocks.SMOOTH_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SMOOTH_SANDSTONE).textureMap(allWithSuffix(Blocks.SANDSTONE, "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.CUT_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_SANDSTONE).textureMap(custom(Blocks.CUT_SANDSTONE, Blocks.SANDSTONE, Blocks.SANDSTONE, "", "_top", "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.RED_SANDSTONE).textureMap(blockTB(Blocks.RED_SANDSTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_RED_SANDSTONE).textureMap(custom(Blocks.CHISELED_RED_SANDSTONE, Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE, "", "_top", "_top")).stonecutting(Blocks.RED_SANDSTONE));
		putInDatagenArgs(ModBlocks.SMOOTH_RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SMOOTH_RED_SANDSTONE).textureMap(allWithSuffix(Blocks.RED_SANDSTONE, "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.CUT_RED_SANDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_RED_SANDSTONE).textureMap(custom(Blocks.CUT_RED_SANDSTONE, Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE, "", "_top", "_top")).stonecutting());
		putInDatagenArgs(ModBlocks.SEA_LANTERN_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SEA_LANTERN).textureMap(TextureMapping.cube(Blocks.SEA_LANTERN)));
		putInDatagenArgs(ModBlocks.PRISMARINE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.PRISMARINE).textureMap(TextureMapping.cube(Blocks.PRISMARINE)).stonecutting());
		putInDatagenArgs(ModBlocks.PRISMARINE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.PRISMARINE_BRICKS).textureMap(TextureMapping.cube(Blocks.PRISMARINE_BRICKS)).stonecutting());
		putInDatagenArgs(ModBlocks.DARK_PRISMARINE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DARK_PRISMARINE).textureMap(TextureMapping.cube(Blocks.DARK_PRISMARINE)).stonecutting());
		putInDatagenArgs(ModBlocks.NETHERRACK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.NETHERRACK).textureMap(TextureMapping.cube(Blocks.NETHERRACK)));
		putInDatagenArgs(ModBlocks.NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.NETHER_BRICKS).textureMap(TextureMapping.cube(Blocks.NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.CRACKED_NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRACKED_NETHER_BRICKS).textureMap(TextureMapping.cube(Blocks.CRACKED_NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.CHISELED_NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_NETHER_BRICKS).textureMap(TextureMapping.cube(Blocks.CHISELED_NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.RED_NETHER_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.RED_NETHER_BRICKS).textureMap(TextureMapping.cube(Blocks.RED_NETHER_BRICKS)));
		putInDatagenArgs(ModBlocks.BASALT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BASALT).textureMap(sideAndTopForEnds(Blocks.BASALT)));
		putInDatagenArgs(ModBlocks.SMOOTH_BASALT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SMOOTH_BASALT).textureMap(TextureMapping.cube(Blocks.SMOOTH_BASALT)));
		putInDatagenArgs(ModBlocks.POLISHED_BASALT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_BASALT).textureMap(sideAndTopForEnds(Blocks.POLISHED_BASALT)));
		putInDatagenArgs(ModBlocks.BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BLACKSTONE).textureMap(blockAndTopForEnds(Blocks.BLACKSTONE)).stonecutting());
		putInDatagenArgs(ModBlocks.GILDED_BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GILDED_BLACKSTONE).textureMap(TextureMapping.cube(Blocks.GILDED_BLACKSTONE)));
		putInDatagenArgs(ModBlocks.CHISELED_POLISHED_BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_POLISHED_BLACKSTONE).textureMap(TextureMapping.cube(Blocks.CHISELED_POLISHED_BLACKSTONE)).stonecutting(Blocks.POLISHED_BLACKSTONE, Blocks.BLACKSTONE));
		putInDatagenArgs(ModBlocks.POLISHED_BLACKSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_BLACKSTONE).textureMap(TextureMapping.cube(Blocks.POLISHED_BLACKSTONE)).stonecutting(Blocks.BLACKSTONE));
		putInDatagenArgs(ModBlocks.POLISHED_BLACKSTONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.POLISHED_BLACKSTONE_BRICKS).textureMap(TextureMapping.cube(Blocks.POLISHED_BLACKSTONE_BRICKS)).stonecutting(Blocks.POLISHED_BLACKSTONE));
		putInDatagenArgs(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS).textureMap(TextureMapping.cube(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)));
		putInDatagenArgs(ModBlocks.END_STONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.END_STONE).textureMap(TextureMapping.cube(Blocks.END_STONE)).stonecutting());
		putInDatagenArgs(ModBlocks.END_STONE_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.END_STONE_BRICKS).textureMap(TextureMapping.cube(Blocks.END_STONE_BRICKS)).stonecutting(Blocks.END_STONE));
		putInDatagenArgs(ModBlocks.PURPUR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.PURPUR_BLOCK).textureMap(TextureMapping.cube(Blocks.PURPUR_BLOCK)));
		putInDatagenArgs(ModBlocks.PURPUR_PILLAR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.PURPUR_PILLAR).textureMap(blockAndTopForEnds(Blocks.PURPUR_PILLAR)));
		putInDatagenArgs(ModBlocks.COAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COAL_BLOCK).textureMap(TextureMapping.cube(Blocks.COAL_BLOCK)));
		putInDatagenArgs(ModBlocks.IRON_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.IRON_BLOCK).textureMap(TextureMapping.cube(Blocks.IRON_BLOCK)));
		putInDatagenArgs(ModBlocks.GOLD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GOLD_BLOCK).textureMap(TextureMapping.cube(Blocks.GOLD_BLOCK)));
		putInDatagenArgs(ModBlocks.REDSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.REDSTONE_BLOCK).textureMap(TextureMapping.cube(Blocks.REDSTONE_BLOCK)));
		putInDatagenArgs(ModBlocks.EMERALD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.EMERALD_BLOCK).textureMap(TextureMapping.cube(Blocks.EMERALD_BLOCK)));
		putInDatagenArgs(ModBlocks.LAPIS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.LAPIS_BLOCK).textureMap(TextureMapping.cube(Blocks.LAPIS_BLOCK)));
		putInDatagenArgs(ModBlocks.DIAMOND_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DIAMOND_BLOCK).textureMap(TextureMapping.cube(Blocks.DIAMOND_BLOCK)));
		putInDatagenArgs(ModBlocks.NETHERITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.NETHERITE_BLOCK).textureMap(TextureMapping.cube(Blocks.NETHERITE_BLOCK)));
		putInDatagenArgs(ModBlocks.QUARTZ_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.QUARTZ_BLOCK).textureMap(blockSTB(Blocks.QUARTZ_BLOCK)).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_QUARTZ_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_QUARTZ_BLOCK).textureMap(blockAndTopForEnds(Blocks.CHISELED_QUARTZ_BLOCK)).stonecutting(Blocks.QUARTZ_BLOCK));
		putInDatagenArgs(ModBlocks.QUARTZ_BRICKS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.QUARTZ_BRICKS).textureMap(TextureMapping.cube(Blocks.QUARTZ_BRICKS)).stonecutting(Blocks.QUARTZ_BLOCK));
		putInDatagenArgs(ModBlocks.QUARTZ_PILLAR_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.QUARTZ_PILLAR).textureMap(blockAndTopForEnds(Blocks.QUARTZ_PILLAR)).stonecutting(Blocks.QUARTZ_BLOCK));
		putInDatagenArgs(ModBlocks.SMOOTH_QUARTZ_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.SMOOTH_QUARTZ).textureMap(allWithSuffix(Blocks.QUARTZ_BLOCK, "_bottom")).stonecutting());
		putInDatagenArgs(ModBlocks.AMETHYST_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.AMETHYST_BLOCK).textureMap(TextureMapping.cube(Blocks.AMETHYST_BLOCK)));
		putInDatagenArgs(ModBlocks.WAXED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.waxed().unaffected(), Blocks.COPPER_BLOCK.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().unaffected())).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.waxed().unaffected(), Blocks.CHISELED_COPPER.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().unaffected())).stonecutting(Blocks.COPPER_BLOCK.waxed().unaffected()));
		putInDatagenArgs(ModBlocks.WAXED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.waxed().unaffected(), Blocks.COPPER_GRATE.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().unaffected())).stonecutting(Blocks.COPPER_BLOCK.waxed().unaffected()));
		putInDatagenArgs(ModBlocks.WAXED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.waxed().unaffected(), Blocks.CUT_COPPER.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().unaffected())).stonecutting(Blocks.COPPER_BLOCK.waxed().unaffected()));
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.waxed().exposed(), Blocks.COPPER_BLOCK.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().exposed())).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.waxed().exposed(), Blocks.CHISELED_COPPER.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().exposed())).stonecutting(Blocks.COPPER_BLOCK.waxed().exposed()));
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.waxed().exposed(), Blocks.COPPER_GRATE.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().exposed())).stonecutting(Blocks.COPPER_BLOCK.waxed().exposed()));
		putInDatagenArgs(ModBlocks.WAXED_EXPOSED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.waxed().exposed(), Blocks.CUT_COPPER.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().exposed())).stonecutting(Blocks.COPPER_BLOCK.waxed().exposed()));
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.waxed().weathered(), Blocks.COPPER_BLOCK.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().weathered())).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.waxed().weathered(), Blocks.CHISELED_COPPER.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().weathered())).stonecutting(Blocks.COPPER_BLOCK.waxed().weathered()));
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.waxed().weathered(), Blocks.COPPER_GRATE.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().weathered())).stonecutting(Blocks.COPPER_BLOCK.waxed().weathered()));
		putInDatagenArgs(ModBlocks.WAXED_WEATHERED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.waxed().weathered(), Blocks.CUT_COPPER.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().weathered())).stonecutting(Blocks.COPPER_BLOCK.waxed().weathered()));
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.waxed().oxidized(), Blocks.COPPER_BLOCK.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().oxidized())).stonecutting());
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.waxed().oxidized(), Blocks.CHISELED_COPPER.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().oxidized())).stonecutting(Blocks.COPPER_BLOCK.waxed().oxidized()));
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.waxed().oxidized(), Blocks.COPPER_GRATE.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().oxidized())).stonecutting(Blocks.COPPER_BLOCK.waxed().oxidized()));
		putInDatagenArgs(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.waxed().oxidized(), Blocks.CUT_COPPER.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().oxidized())).stonecutting(Blocks.COPPER_BLOCK.waxed().oxidized()));
		putInDatagenArgs(ModBlocks.EXPOSED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().exposed())).stonecutting());
		putInDatagenArgs(ModBlocks.EXPOSED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().exposed())).stonecutting(Blocks.COPPER_BLOCK.weathering().exposed()));
		putInDatagenArgs(ModBlocks.EXPOSED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().exposed())).stonecutting(Blocks.COPPER_BLOCK.weathering().exposed()));
		putInDatagenArgs(ModBlocks.EXPOSED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.weathering().exposed()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().exposed())).stonecutting(Blocks.COPPER_BLOCK.weathering().exposed()));
		putInDatagenArgs(ModBlocks.WEATHERED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().weathered())).stonecutting());
		putInDatagenArgs(ModBlocks.WEATHERED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().weathered())).stonecutting(Blocks.COPPER_BLOCK.weathering().weathered()));
		putInDatagenArgs(ModBlocks.WEATHERED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().weathered())).stonecutting(Blocks.COPPER_BLOCK.weathering().weathered()));
		putInDatagenArgs(ModBlocks.WEATHERED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.weathering().weathered()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().weathered())).stonecutting(Blocks.COPPER_BLOCK.weathering().weathered()));
		putInDatagenArgs(ModBlocks.OXIDIZED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().oxidized())).stonecutting());
		putInDatagenArgs(ModBlocks.OXIDIZED_CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().oxidized())).stonecutting(Blocks.COPPER_BLOCK.weathering().oxidized()));
		putInDatagenArgs(ModBlocks.OXIDIZED_COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().oxidized())).stonecutting(Blocks.COPPER_BLOCK.weathering().oxidized()));
		putInDatagenArgs(ModBlocks.OXIDIZED_CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.weathering().oxidized()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().oxidized())).stonecutting(Blocks.COPPER_BLOCK.weathering().oxidized()));
		putInDatagenArgs(ModBlocks.COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_BLOCK.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.COPPER_BLOCK.weathering().unaffected())).stonecutting());
		putInDatagenArgs(ModBlocks.CHISELED_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CHISELED_COPPER.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.CHISELED_COPPER.weathering().unaffected())).stonecutting(Blocks.COPPER_BLOCK.weathering().unaffected()));
		putInDatagenArgs(ModBlocks.COPPER_GRATE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_GRATE.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.COPPER_GRATE.weathering().unaffected())).stonecutting(Blocks.COPPER_BLOCK.weathering().unaffected()));
		putInDatagenArgs(ModBlocks.CUT_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CUT_COPPER.weathering().unaffected()).textureMap(TextureMapping.cube(Blocks.CUT_COPPER.weathering().unaffected())).stonecutting(Blocks.COPPER_BLOCK.weathering().unaffected()));
		putInDatagenArgs(ModBlocks.WHITE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.WHITE)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.WHITE))));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.LIGHT_GRAY)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.LIGHT_GRAY))));
		putInDatagenArgs(ModBlocks.GRAY_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.GRAY)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.GRAY))));
		putInDatagenArgs(ModBlocks.BLACK_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.BLACK)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.BLACK))));
		putInDatagenArgs(ModBlocks.BROWN_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.BROWN)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.BROWN))));
		putInDatagenArgs(ModBlocks.RED_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.RED)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.RED))));
		putInDatagenArgs(ModBlocks.ORANGE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.ORANGE)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.ORANGE))));
		putInDatagenArgs(ModBlocks.YELLOW_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.YELLOW)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.YELLOW))));
		putInDatagenArgs(ModBlocks.LIME_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.LIME)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.LIME))));
		putInDatagenArgs(ModBlocks.GREEN_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.GREEN)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.GREEN))));
		putInDatagenArgs(ModBlocks.CYAN_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.CYAN)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.CYAN))));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.LIGHT_BLUE)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.LIGHT_BLUE))));
		putInDatagenArgs(ModBlocks.BLUE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.BLUE)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.BLUE))));
		putInDatagenArgs(ModBlocks.PURPLE_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.PURPLE)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.PURPLE))));
		putInDatagenArgs(ModBlocks.MAGENTA_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.MAGENTA)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.MAGENTA))));
		putInDatagenArgs(ModBlocks.PINK_WOOL_LAYER, new DatagenArgs().blockTags(BlockTags.WOOL).parentBlock(Blocks.WOOL.pick(DyeColor.PINK)).textureMap(TextureMapping.cube(Blocks.WOOL.pick(DyeColor.PINK))));
		putInDatagenArgs(ModBlocks.TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.TERRACOTTA).textureMap(TextureMapping.cube(Blocks.TERRACOTTA)));
		putInDatagenArgs(ModBlocks.WHITE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.WHITE)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.WHITE))));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.LIGHT_GRAY)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.LIGHT_GRAY))));
		putInDatagenArgs(ModBlocks.GRAY_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.GRAY)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.GRAY))));
		putInDatagenArgs(ModBlocks.BLACK_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.BLACK)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.BLACK))));
		putInDatagenArgs(ModBlocks.BROWN_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.BROWN)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.BROWN))));
		putInDatagenArgs(ModBlocks.RED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.RED)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.RED))));
		putInDatagenArgs(ModBlocks.ORANGE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.ORANGE)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.ORANGE))));
		putInDatagenArgs(ModBlocks.YELLOW_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.YELLOW)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.YELLOW))));
		putInDatagenArgs(ModBlocks.LIME_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.LIME)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.LIME))));
		putInDatagenArgs(ModBlocks.GREEN_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.GREEN)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.GREEN))));
		putInDatagenArgs(ModBlocks.CYAN_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.CYAN)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.CYAN))));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.LIGHT_BLUE)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.LIGHT_BLUE))));
		putInDatagenArgs(ModBlocks.BLUE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.BLUE)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.BLUE))));
		putInDatagenArgs(ModBlocks.PURPLE_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.PURPLE)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.PURPLE))));
		putInDatagenArgs(ModBlocks.MAGENTA_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.MAGENTA)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.MAGENTA))));
		putInDatagenArgs(ModBlocks.PINK_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.TERRACOTTA).parentBlock(Blocks.DYED_TERRACOTTA.pick(DyeColor.PINK)).textureMap(TextureMapping.cube(Blocks.DYED_TERRACOTTA.pick(DyeColor.PINK))));
		putInDatagenArgs(ModBlocks.WHITE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.WHITE)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.WHITE))));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.LIGHT_GRAY)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.LIGHT_GRAY))));
		putInDatagenArgs(ModBlocks.GRAY_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.GRAY)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.GRAY))));
		putInDatagenArgs(ModBlocks.BLACK_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.BLACK)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.BLACK))));
		putInDatagenArgs(ModBlocks.BROWN_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.BROWN)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.BROWN))));
		putInDatagenArgs(ModBlocks.RED_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.RED)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.RED))));
		putInDatagenArgs(ModBlocks.ORANGE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.ORANGE)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.ORANGE))));
		putInDatagenArgs(ModBlocks.YELLOW_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.YELLOW)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.YELLOW))));
		putInDatagenArgs(ModBlocks.LIME_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.LIME)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.LIME))));
		putInDatagenArgs(ModBlocks.GREEN_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.GREEN)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.GREEN))));
		putInDatagenArgs(ModBlocks.CYAN_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.CYAN)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.CYAN))));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.LIGHT_BLUE)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.LIGHT_BLUE))));
		putInDatagenArgs(ModBlocks.BLUE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.BLUE)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.BLUE))));
		putInDatagenArgs(ModBlocks.PURPLE_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.PURPLE)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.PURPLE))));
		putInDatagenArgs(ModBlocks.MAGENTA_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.MAGENTA)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.MAGENTA))));
		putInDatagenArgs(ModBlocks.PINK_CONCRETE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CONCRETE.pick(DyeColor.PINK)).textureMap(TextureMapping.cube(Blocks.CONCRETE.pick(DyeColor.PINK))));
		putInDatagenArgs(ModBlocks.WHITE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.WHITE)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.WHITE))));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.LIGHT_GRAY)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.LIGHT_GRAY))));
		putInDatagenArgs(ModBlocks.GRAY_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.GRAY)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.GRAY))));
		putInDatagenArgs(ModBlocks.BLACK_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.BLACK)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.BLACK))));
		putInDatagenArgs(ModBlocks.BROWN_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.BROWN)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.BROWN))));
		putInDatagenArgs(ModBlocks.RED_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.RED)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.RED))));
		putInDatagenArgs(ModBlocks.ORANGE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.ORANGE)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.ORANGE))));
		putInDatagenArgs(ModBlocks.YELLOW_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.YELLOW)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.YELLOW))));
		putInDatagenArgs(ModBlocks.LIME_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.LIME)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.LIME))));
		putInDatagenArgs(ModBlocks.GREEN_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.GREEN)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.GREEN))));
		putInDatagenArgs(ModBlocks.CYAN_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.CYAN)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.CYAN))));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.LIGHT_BLUE)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.LIGHT_BLUE))));
		putInDatagenArgs(ModBlocks.BLUE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.BLUE)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.BLUE))));
		putInDatagenArgs(ModBlocks.PURPLE_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.PURPLE)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.PURPLE))));
		putInDatagenArgs(ModBlocks.MAGENTA_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.MAGENTA)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.MAGENTA))));
		putInDatagenArgs(ModBlocks.PINK_CONCRETE_POWDER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CONCRETE_POWDER.pick(DyeColor.PINK)).textureMap(TextureMapping.cube(Blocks.CONCRETE_POWDER.pick(DyeColor.PINK))));
		putInDatagenArgs(ModBlocks.WHITE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.WHITE)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.WHITE))));
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.LIGHT_GRAY)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.LIGHT_GRAY))));
		putInDatagenArgs(ModBlocks.GRAY_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.GRAY)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.GRAY))));
		putInDatagenArgs(ModBlocks.BLACK_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.BLACK)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.BLACK))));
		putInDatagenArgs(ModBlocks.BROWN_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.BROWN)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.BROWN))));
		putInDatagenArgs(ModBlocks.RED_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.RED)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.RED))));
		putInDatagenArgs(ModBlocks.ORANGE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.ORANGE)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.ORANGE))));
		putInDatagenArgs(ModBlocks.YELLOW_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.YELLOW)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.YELLOW))));
		putInDatagenArgs(ModBlocks.LIME_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.LIME)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.LIME))));
		putInDatagenArgs(ModBlocks.GREEN_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.GREEN)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.GREEN))));
		putInDatagenArgs(ModBlocks.CYAN_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.CYAN)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.CYAN))));
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.LIGHT_BLUE)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.LIGHT_BLUE))));
		putInDatagenArgs(ModBlocks.BLUE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.BLUE)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.BLUE))));
		putInDatagenArgs(ModBlocks.PURPLE_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.PURPLE)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.PURPLE))));
		putInDatagenArgs(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.MAGENTA)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.MAGENTA))));
		putInDatagenArgs(ModBlocks.PINK_GLAZED_TERRACOTTA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.PINK)).textureMap(TextureMapping.cube(Blocks.GLAZED_TERRACOTTA.pick(DyeColor.PINK))));
		putInDatagenArgs(ModBlocks.GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLASS).textureMap(TextureMapping.cube(Blocks.GLASS)).needsSilkTouch());
		putInDatagenArgs(ModBlocks.TINTED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.TINTED_GLASS).textureMap(TextureMapping.cube(Blocks.TINTED_GLASS)));
		putInDatagenArgs(ModBlocks.WHITE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.WHITE)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.WHITE))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.LIGHT_GRAY_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.LIGHT_GRAY)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.LIGHT_GRAY))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.GRAY_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.GRAY)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.GRAY))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.BLACK_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.BLACK)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.BLACK))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.BROWN_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.BROWN)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.BROWN))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.RED_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.RED)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.RED))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.ORANGE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.ORANGE)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.ORANGE))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.YELLOW_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.YELLOW)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.YELLOW))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.LIME_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.LIME)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.LIME))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.GREEN_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.GREEN)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.GREEN))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.CYAN_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.CYAN)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.CYAN))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.LIGHT_BLUE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.LIGHT_BLUE)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.LIGHT_BLUE))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.BLUE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.BLUE)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.BLUE))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.PURPLE_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.PURPLE)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.PURPLE))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.MAGENTA_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.MAGENTA)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.MAGENTA))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.PINK_STAINED_GLASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.STAINED_GLASS.pick(DyeColor.PINK)).textureMap(TextureMapping.cube(Blocks.STAINED_GLASS.pick(DyeColor.PINK))).needsSilkTouch());
		putInDatagenArgs(ModBlocks.DIRT_PATH_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.DIRT_PATH).textureMap(custom(Blocks.DIRT_PATH, Blocks.DIRT_PATH, Blocks.DIRT, "_side", "_top", "")).y15());
		putInDatagenArgs(ModBlocks.FARMLAND_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.FARMLAND).textureMap(custom(Blocks.DIRT, Blocks.FARMLAND, Blocks.DIRT, "", "", "")).y15());
		putInDatagenArgs(ModBlocks.DIRT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.DIRT).textureMap(TextureMapping.cube(Blocks.DIRT)));
		putInDatagenArgs(ModBlocks.GRASS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.GRASS_BLOCK).tintSource(new GrassColorSource()));
		putInDatagenArgs(ModBlocks.PODZOL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.PODZOL).textureMap(custom(Blocks.PODZOL, Blocks.PODZOL, Blocks.DIRT, "_side", "_top", "")));
		putInDatagenArgs(ModBlocks.MYCELIUM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.MYCELIUM).textureMap(custom(Blocks.MYCELIUM, Blocks.MYCELIUM, Blocks.DIRT, "_side", "_top", "")));
		putInDatagenArgs(ModBlocks.COARSE_DIRT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.COARSE_DIRT).textureMap(TextureMapping.cube(Blocks.COARSE_DIRT)));
		putInDatagenArgs(ModBlocks.ROOTED_DIRT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.ROOTED_DIRT).textureMap(TextureMapping.cube(Blocks.ROOTED_DIRT)));
		putInDatagenArgs(ModBlocks.MUD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.MUD).textureMap(TextureMapping.cube(Blocks.MUD)));
		putInDatagenArgs(ModBlocks.MUDDY_MANGROVE_ROOTS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.MUDDY_MANGROVE_ROOTS).textureMap(sideAndTopForEnds(Blocks.MUDDY_MANGROVE_ROOTS)));
		putInDatagenArgs(ModBlocks.CLAY_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.CLAY).textureMap(TextureMapping.cube(Blocks.CLAY)));
		putInDatagenArgs(ModBlocks.GRAVEL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.GRAVEL).textureMap(TextureMapping.cube(Blocks.GRAVEL)));
		putInDatagenArgs(ModBlocks.SAND_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.SAND).textureMap(TextureMapping.cube(Blocks.SAND)));
		putInDatagenArgs(ModBlocks.RED_SAND_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.RED_SAND).textureMap(TextureMapping.cube(Blocks.RED_SAND)));
		putInDatagenArgs(ModBlocks.ICE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.ICE).textureMap(TextureMapping.cube(Blocks.ICE)));
		putInDatagenArgs(ModBlocks.PACKED_ICE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.PACKED_ICE).textureMap(TextureMapping.cube(Blocks.PACKED_ICE)));
		putInDatagenArgs(ModBlocks.BLUE_ICE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BLUE_ICE).textureMap(TextureMapping.cube(Blocks.BLUE_ICE)));
		putInDatagenArgs(ModBlocks.SNOW_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.SNOW_BLOCK).textureMap(TextureMapping.cube(Blocks.SNOW)));
		putInDatagenArgs(ModBlocks.MOSS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.MOSS_BLOCK).textureMap(TextureMapping.cube(Blocks.MOSS_BLOCK)));
		putInDatagenArgs(ModBlocks.PALE_MOSS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.PALE_MOSS_BLOCK).textureMap(TextureMapping.cube(Blocks.PALE_MOSS_BLOCK)));
		putInDatagenArgs(ModBlocks.CALCITE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CALCITE).textureMap(TextureMapping.cube(Blocks.CALCITE)));
		putInDatagenArgs(ModBlocks.DRIPSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DRIPSTONE_BLOCK).textureMap(TextureMapping.cube(Blocks.DRIPSTONE_BLOCK)));
		putInDatagenArgs(ModBlocks.MAGMA_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.MAGMA_BLOCK).textureMap(TextureMapping.cube(new Material(Identifier.withDefaultNamespace("block/magma")))));
		putInDatagenArgs(ModBlocks.OBSIDIAN_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.OBSIDIAN).textureMap(TextureMapping.cube(Blocks.OBSIDIAN)));
		putInDatagenArgs(ModBlocks.CRYING_OBSIDIAN_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRYING_OBSIDIAN).textureMap(TextureMapping.cube(Blocks.CRYING_OBSIDIAN)));
		putInDatagenArgs(ModBlocks.CRIMSON_NYLIUM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.CRIMSON_NYLIUM).textureMap(custom(Blocks.CRIMSON_NYLIUM, Blocks.CRIMSON_NYLIUM, Blocks.NETHERRACK, "_side", "", "")));
		putInDatagenArgs(ModBlocks.WARPED_NYLIUM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.WARPED_NYLIUM).textureMap(custom(Blocks.WARPED_NYLIUM, Blocks.WARPED_NYLIUM, Blocks.NETHERRACK, "_side", "", "")));
		putInDatagenArgs(ModBlocks.SOUL_SAND_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.SOUL_SAND).textureMap(TextureMapping.cube(Blocks.SOUL_SAND)));
		putInDatagenArgs(ModBlocks.SOUL_SOIL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_SHOVEL).parentBlock(Blocks.SOUL_SOIL).textureMap(TextureMapping.cube(Blocks.SOUL_SOIL)));
		putInDatagenArgs(ModBlocks.BONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BONE_BLOCK).textureMap(sideAndTopForEnds(Blocks.BONE_BLOCK)));
		putInDatagenArgs(ModBlocks.COAL_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COAL_ORE).textureMap(TextureMapping.cube(Blocks.COAL_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_COAL_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_COAL_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_COAL_ORE)));
		putInDatagenArgs(ModBlocks.IRON_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.IRON_ORE).textureMap(TextureMapping.cube(Blocks.IRON_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_IRON_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_IRON_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_IRON_ORE)));
		putInDatagenArgs(ModBlocks.COPPER_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.COPPER_ORE).textureMap(TextureMapping.cube(Blocks.COPPER_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_COPPER_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_COPPER_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_COPPER_ORE)));
		putInDatagenArgs(ModBlocks.GOLD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GOLD_ORE).textureMap(TextureMapping.cube(Blocks.GOLD_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_GOLD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_GOLD_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_GOLD_ORE)));
		putInDatagenArgs(ModBlocks.REDSTONE_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.REDSTONE_ORE).textureMap(TextureMapping.cube(Blocks.REDSTONE_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_REDSTONE_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_REDSTONE_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_REDSTONE_ORE)));
		putInDatagenArgs(ModBlocks.EMERALD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.EMERALD_ORE).textureMap(TextureMapping.cube(Blocks.EMERALD_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_EMERALD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_EMERALD_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_EMERALD_ORE)));
		putInDatagenArgs(ModBlocks.LAPIS_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.LAPIS_ORE).textureMap(TextureMapping.cube(Blocks.LAPIS_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_LAPIS_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_LAPIS_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_LAPIS_ORE)));
		putInDatagenArgs(ModBlocks.DIAMOND_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DIAMOND_ORE).textureMap(TextureMapping.cube(Blocks.DIAMOND_ORE)));
		putInDatagenArgs(ModBlocks.DEEPSLATE_DIAMOND_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEEPSLATE_DIAMOND_ORE).textureMap(TextureMapping.cube(Blocks.DEEPSLATE_DIAMOND_ORE)));
		putInDatagenArgs(ModBlocks.NETHER_GOLD_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.NETHER_GOLD_ORE).textureMap(TextureMapping.cube(Blocks.NETHER_GOLD_ORE)));
		putInDatagenArgs(ModBlocks.NETHER_QUARTZ_ORE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.NETHER_QUARTZ_ORE).textureMap(TextureMapping.cube(Blocks.NETHER_QUARTZ_ORE)));
		putInDatagenArgs(ModBlocks.ANCIENT_DEBRIS_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.ANCIENT_DEBRIS).textureMap(sideAndTopForEnds(Blocks.ANCIENT_DEBRIS)));
		putInDatagenArgs(ModBlocks.RAW_IRON_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.RAW_IRON_BLOCK).textureMap(TextureMapping.cube(Blocks.RAW_IRON_BLOCK)));
		putInDatagenArgs(ModBlocks.RAW_COPPER_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.RAW_COPPER_BLOCK).textureMap(TextureMapping.cube(Blocks.RAW_COPPER_BLOCK)));
		putInDatagenArgs(ModBlocks.RAW_GOLD_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.RAW_GOLD_BLOCK).textureMap(TextureMapping.cube(Blocks.RAW_GOLD_BLOCK)));
		putInDatagenArgs(ModBlocks.GLOWSTONE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.GLOWSTONE).textureMap(TextureMapping.cube(Blocks.GLOWSTONE)));
		putInDatagenArgs(ModBlocks.OAK_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.OAK_LEAVES).textureMap(TextureMapping.cube(Blocks.OAK_LEAVES)).tintSource(new Constant(-12012264)));
		putInDatagenArgs(ModBlocks.SPRUCE_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.SPRUCE_LEAVES).textureMap(TextureMapping.cube(Blocks.SPRUCE_LEAVES)).tintSource(new Constant(-10380959)));
		putInDatagenArgs(ModBlocks.BIRCH_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.BIRCH_LEAVES).textureMap(TextureMapping.cube(Blocks.BIRCH_LEAVES)).tintSource(new Constant(-8345771)));
		putInDatagenArgs(ModBlocks.JUNGLE_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.JUNGLE_LEAVES).textureMap(TextureMapping.cube(Blocks.JUNGLE_LEAVES)).tintSource(new Constant(-12012264)));
		putInDatagenArgs(ModBlocks.ACACIA_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.ACACIA_LEAVES).textureMap(TextureMapping.cube(Blocks.ACACIA_LEAVES)).tintSource(new Constant(-12012264)));
		putInDatagenArgs(ModBlocks.DARK_OAK_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.DARK_OAK_LEAVES).textureMap(TextureMapping.cube(Blocks.DARK_OAK_LEAVES)).tintSource(new Constant(-12012264)));
		putInDatagenArgs(ModBlocks.MANGROVE_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.MANGROVE_LEAVES).textureMap(TextureMapping.cube(Blocks.MANGROVE_LEAVES)).tintSource(new Constant(-7158200)));
		putInDatagenArgs(ModBlocks.CHERRY_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.CHERRY_LEAVES).textureMap(TextureMapping.cube(Blocks.CHERRY_LEAVES)));
		putInDatagenArgs(ModBlocks.PALE_OAK_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.PALE_OAK_LEAVES).textureMap(TextureMapping.cube(Blocks.PALE_OAK_LEAVES)));
		putInDatagenArgs(ModBlocks.AZALEA_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.AZALEA_LEAVES).textureMap(TextureMapping.cube(Blocks.AZALEA_LEAVES)));
		putInDatagenArgs(ModBlocks.FLOWERING_AZALEA_LEAVES_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.FLOWERING_AZALEA_LEAVES).textureMap(TextureMapping.cube(Blocks.FLOWERING_AZALEA_LEAVES)));
		putInDatagenArgs(ModBlocks.BROWN_MUSHROOM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.BROWN_MUSHROOM_BLOCK));
		putInDatagenArgs(ModBlocks.RED_MUSHROOM_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.RED_MUSHROOM_BLOCK));
		putInDatagenArgs(ModBlocks.NETHER_WART_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.NETHER_WART_BLOCK).textureMap(TextureMapping.cube(Blocks.NETHER_WART_BLOCK)));
		putInDatagenArgs(ModBlocks.WARPED_WART_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.WARPED_WART_BLOCK).textureMap(TextureMapping.cube(Blocks.WARPED_WART_BLOCK)));
		putInDatagenArgs(ModBlocks.SHROOMLIGHT_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.SHROOMLIGHT).textureMap(TextureMapping.cube(Blocks.SHROOMLIGHT)));
		putInDatagenArgs(ModBlocks.DRIED_KELP_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.DRIED_KELP_BLOCK).textureMap(blockSTB(Identifier.withDefaultNamespace("block/dried_kelp"))));
		putInDatagenArgs(ModBlocks.TUBE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.TUBE_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.TUBE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.BRAIN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BRAIN_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.BRAIN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.BUBBLE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.BUBBLE_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.BUBBLE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.FIRE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.FIRE_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.FIRE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.HORN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.HORN_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.HORN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_TUBE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEAD_TUBE_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.DEAD_TUBE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_BRAIN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEAD_BRAIN_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.DEAD_BRAIN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_BUBBLE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEAD_BUBBLE_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.DEAD_BUBBLE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_FIRE_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEAD_FIRE_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.DEAD_FIRE_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.DEAD_HORN_CORAL_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_PICKAXE).parentBlock(Blocks.DEAD_HORN_CORAL_BLOCK).textureMap(TextureMapping.cube(Blocks.DEAD_HORN_CORAL_BLOCK)));
		putInDatagenArgs(ModBlocks.SPONGE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.SPONGE).textureMap(TextureMapping.cube(Blocks.SPONGE)));
		putInDatagenArgs(ModBlocks.WET_SPONGE_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.WET_SPONGE).textureMap(TextureMapping.cube(Blocks.WET_SPONGE)));
		putInDatagenArgs(ModBlocks.MELON_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.MELON).textureMap(sideAndTopForEnds(Blocks.MELON)));
		putInDatagenArgs(ModBlocks.PUMPKIN_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_AXE).parentBlock(Blocks.PUMPKIN).textureMap(sideAndTopForEnds(Blocks.PUMPKIN)));
		putInDatagenArgs(ModBlocks.HAY_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.HAY_BLOCK).textureMap(sideAndTopForEnds(Blocks.HAY_BLOCK)));
		putInDatagenArgs(ModBlocks.HONEYCOMB_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.HONEYCOMB_BLOCK).textureMap(TextureMapping.cube(Blocks.HONEYCOMB_BLOCK)));
		putInDatagenArgs(ModBlocks.SLIME_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.SLIME_BLOCK).textureMap(TextureMapping.cube(Blocks.SLIME_BLOCK)));
		putInDatagenArgs(ModBlocks.HONEY_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.HONEY_BLOCK).textureMap(blockSTB(Blocks.HONEY_BLOCK)));
		putInDatagenArgs(ModBlocks.RESIN_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.RESIN_BLOCK).textureMap(TextureMapping.cube(Blocks.RESIN_BLOCK)));
		putInDatagenArgs(ModBlocks.OCHRE_FROGLIGHT_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.OCHRE_FROGLIGHT).textureMap(sideAndTopForEnds(Blocks.OCHRE_FROGLIGHT)));
		putInDatagenArgs(ModBlocks.VERDANT_FROGLIGHT_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.VERDANT_FROGLIGHT).textureMap(sideAndTopForEnds(Blocks.VERDANT_FROGLIGHT)));
		putInDatagenArgs(ModBlocks.PEARLESCENT_FROGLIGHT_LAYER, new DatagenArgs().blockTags().parentBlock(Blocks.PEARLESCENT_FROGLIGHT).textureMap(sideAndTopForEnds(Blocks.PEARLESCENT_FROGLIGHT)));
		putInDatagenArgs(ModBlocks.SCULK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.SCULK).textureMap(TextureMapping.cube(Blocks.SCULK)));
		putInDatagenArgs(ModBlocks.BEDROCK_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.BEDROCK).textureMap(TextureMapping.cube(Blocks.BEDROCK)));
		putInDatagenArgs(ModBlocks.TARGET_LAYER, new DatagenArgs().blockTags(BlockTags.MINEABLE_WITH_HOE).parentBlock(Blocks.TARGET).textureMap(sideAndTopForEnds(Blocks.TARGET)));
	}

	public static void registerRegistryArgs() {
		putInRegistryArgs(ModBlocks.OAK_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.OAK_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_OAK_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.OAK_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_OAK_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_OAK_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_OAK_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.SPRUCE_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.SPRUCE_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_SPRUCE_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.SPRUCE_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_SPRUCE_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_SPRUCE_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_SPRUCE_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.BIRCH_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.BIRCH_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_BIRCH_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.BIRCH_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_BIRCH_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_BIRCH_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_BIRCH_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.JUNGLE_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.JUNGLE_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_JUNGLE_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.JUNGLE_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_JUNGLE_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_JUNGLE_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_JUNGLE_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.ACACIA_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.ACACIA_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_ACACIA_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.ACACIA_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_ACACIA_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_ACACIA_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_ACACIA_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.DARK_OAK_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.DARK_OAK_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_DARK_OAK_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.DARK_OAK_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_DARK_OAK_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_DARK_OAK_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_DARK_OAK_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.MANGROVE_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.MANGROVE_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_MANGROVE_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.MANGROVE_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_MANGROVE_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_MANGROVE_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_MANGROVE_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.CHERRY_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.CHERRY_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CHERRY_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.CHERRY_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CHERRY_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_CHERRY_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_CHERRY_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.PALE_OAK_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.PALE_OAK_LOG_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_PALE_OAK_LOG_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.PALE_OAK_WOOD_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_PALE_OAK_WOOD_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_PALE_OAK_LOG_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_PALE_OAK_WOOD_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.BAMBOO_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.BAMBOO_MOSAIC_LAYER, new RegistryArgs().flammable(5, 20));
		putInRegistryArgs(ModBlocks.BAMBOO_BLOCK_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_BAMBOO_BLOCK_LAYER).flammable(5, 5));
		putInRegistryArgs(ModBlocks.STRIPPED_BAMBOO_BLOCK_LAYER, new RegistryArgs().flammable(5, 5));
		putInRegistryArgs(ModBlocks.CRIMSON_STEM_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CRIMSON_STEM_LAYER));
		putInRegistryArgs(ModBlocks.CRIMSON_HYPHAE_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_CRIMSON_HYPHAE_LAYER));
		putInRegistryArgs(ModBlocks.WARPED_STEM_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_WARPED_STEM_LAYER));
		putInRegistryArgs(ModBlocks.WARPED_HYPHAE_LAYER, new RegistryArgs().stripped(ModBlocks.STRIPPED_WARPED_HYPHAE_LAYER));
		putInRegistryArgs(ModBlocks.WAXED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WAXED_EXPOSED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WAXED_WEATHERED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WAXED_OXIDIZED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.EXPOSED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WEATHERED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.OXIDIZED_COPPER_GRATE_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.COPPER_LAYER, new RegistryArgs().oxidizable(ModBlocks.EXPOSED_COPPER_LAYER, ModBlocks.WEATHERED_COPPER_LAYER, ModBlocks.OXIDIZED_COPPER_LAYER, ModBlocks.WAXED_COPPER_LAYER, ModBlocks.WAXED_EXPOSED_COPPER_LAYER, ModBlocks.WAXED_WEATHERED_COPPER_LAYER, ModBlocks.WAXED_OXIDIZED_COPPER_LAYER));
		putInRegistryArgs(ModBlocks.CHISELED_COPPER_LAYER, new RegistryArgs().oxidizable(ModBlocks.EXPOSED_CHISELED_COPPER_LAYER, ModBlocks.WEATHERED_CHISELED_COPPER_LAYER, ModBlocks.OXIDIZED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_EXPOSED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_WEATHERED_CHISELED_COPPER_LAYER, ModBlocks.WAXED_OXIDIZED_CHISELED_COPPER_LAYER));
		putInRegistryArgs(ModBlocks.COPPER_GRATE_LAYER, new RegistryArgs().transparent().oxidizable(ModBlocks.EXPOSED_COPPER_GRATE_LAYER, ModBlocks.WEATHERED_COPPER_GRATE_LAYER, ModBlocks.OXIDIZED_COPPER_GRATE_LAYER, ModBlocks.WAXED_COPPER_GRATE_LAYER, ModBlocks.WEATHERED_COPPER_GRATE_LAYER, ModBlocks.WAXED_WEATHERED_COPPER_GRATE_LAYER, ModBlocks.WAXED_OXIDIZED_COPPER_GRATE_LAYER));
		putInRegistryArgs(ModBlocks.CUT_COPPER_LAYER, new RegistryArgs().oxidizable(ModBlocks.EXPOSED_CUT_COPPER_LAYER, ModBlocks.WEATHERED_CUT_COPPER_LAYER, ModBlocks.OXIDIZED_CUT_COPPER_LAYER, ModBlocks.WAXED_CUT_COPPER_LAYER, ModBlocks.WAXED_EXPOSED_CUT_COPPER_LAYER, ModBlocks.WAXED_WEATHERED_CUT_COPPER_LAYER, ModBlocks.WAXED_OXIDIZED_CUT_COPPER_LAYER));
		putInRegistryArgs(ModBlocks.GLASS_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.TINTED_GLASS_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.WHITE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.LIGHT_GRAY_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.GRAY_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BLACK_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BROWN_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.RED_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.ORANGE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.YELLOW_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.LIME_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.GREEN_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.CYAN_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.LIGHT_BLUE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BLUE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PURPLE_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.MAGENTA_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PINK_STAINED_GLASS_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.DIRT_LAYER, new RegistryArgs().tillable(ModBlocks.FARMLAND_LAYER).flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.GRASS_LAYER, new RegistryArgs().transparent().grassTinted().flattenable(ModBlocks.DIRT_PATH_LAYER).tillable(ModBlocks.FARMLAND_LAYER));
		putInRegistryArgs(ModBlocks.PODZOL_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.MYCELIUM_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.COARSE_DIRT_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.ROOTED_DIRT_LAYER, new RegistryArgs().flattenable(ModBlocks.DIRT_PATH_LAYER));
		putInRegistryArgs(ModBlocks.ICE_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PACKED_ICE_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.BLUE_ICE_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.PALE_MOSS_LAYER, new RegistryArgs().flammable(5, 100));
		putInRegistryArgs(ModBlocks.OAK_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.SPRUCE_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.BIRCH_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.JUNGLE_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.ACACIA_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.DARK_OAK_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.MANGROVE_LEAVES_LAYER, new RegistryArgs().transparent().foliageTinted());
		putInRegistryArgs(ModBlocks.CHERRY_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.PALE_OAK_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.AZALEA_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.FLOWERING_AZALEA_LEAVES_LAYER, new RegistryArgs().transparent());
		putInRegistryArgs(ModBlocks.SLIME_LAYER, new RegistryArgs().translucent());
		putInRegistryArgs(ModBlocks.HONEY_LAYER, new RegistryArgs().translucent());
	}
}
