# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=4.0.0+26.2
maven_group=net.fellter.vanillalayerplus
archives_base_name=vanillalayerplus

# Dependencies
fabric_version=0.156.0+26.2